# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 8afb4eb26ed121cc3f599631eec4afbe7ed027ddaa62668310a649db7f3491bb307c050593b94aa929251b514db1c89497e3851069dca4cf15240e0b0ab08fdd

test:
  secret_key_base: 5a7d3635d48e688a29ff9b5989fc70e966f23b36ec4864c75f1d116c7a4399a5a67a36075ebfb2a011c60ba36dec0a6e0347a75f88afac209eb34cb59ff07736

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
